### ISSUE TITLE
Not sure what to do after making a copy of the script

### ISSUE THREAD

**Issue by jonleung** [mastahyeti/OctoGAS#15]
I try to:

1. Click Publish
2. Deploy as Webapp
3. When I open the current webapp URL, I get this:

> ![image](https://cloud.githubusercontent.com/assets/654941/10804680/f76f497e-7d85-11e5-8673-82f39b5b112b.png)

**Comment by mastahyeti** [comment]
If you want to run the webapp, you need to [register](https://github.com/settings/applications/new) an OAuth application on GitHub.com. You'll then need to put the client id/secret in the project properties on Google Apps Scripts:

<img width="1017" alt="2015-10-29 at 9 11 am" src="https://cloud.githubusercontent.com/assets/1144197/10822518/3f1b84a8-7e1d-11e5-9cd0-1f171390fc26.png">

**Comment by jonleung** [comment]
Thanks!
