### ISSUE TITLE
GitHub oauth error

### ISSUE THREAD

**Issue by probablycorey** [mastahyeti/OctoGAS#18]
On Chrome 51, when I click the 'Authorize with GitHub' button I get a policy error.

![img](https://probablycorey-monosnap.s3.amazonaws.com/httpsscript.google.commacrossAKfycbyTt-wRFUb-O6WkoamJUPdAS8LMeQ-tbl_k2dIXP4WKAyGvlZr1exec_2016-07-12_10-42-47.png)

Then I see this page.

![img](https://probablycorey-monosnap.s3.amazonaws.com/httpsscript.google.commacrossAKfycbyTt-wRFUb-O6WkoamJUPdAS8LMeQ-tbl_k2dIXP4WKAyGvlZr1exec_2016-07-12_10-43-46.png)

> Refused to display 'https://github.com/login/oauth/authorize?...' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

**Comment by durandom** [comment]
one workaround is to open the link in a new tab

**Comment by mastahyeti** [comment]
#19 should fix this. Let me know if it doesn't.
